# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target '唯独影院' do

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'

end
